# Generated by Django 3.2 on 2021-08-07 17:24

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id_composition', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('not_defined', 'Не выбрано'), ('movie', 'Фильм'), ('series', 'Сериал'), ('show', 'Шоу')], default='not_defined', max_length=50, verbose_name='Тип')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('name_eng', models.CharField(max_length=100, verbose_name='Английское название')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True, verbose_name='Сезон')),
                ('episodes', models.IntegerField(blank=True, null=True, verbose_name='Эпизоды')),
                ('last_watched', models.IntegerField(blank=True, null=True, verbose_name='Последний просмотренный')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('rating_my', models.FloatField(blank=True, default=0, null=True, verbose_name='Мой рейтинг')),
                ('url_kinopoisk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кинопоиск')),
                ('url_doramatv', models.CharField(blank=True, max_length=100, null=True, verbose_name='ДорамаТВ')),
                ('status', models.CharField(choices=[('to_watch', 'Посмотреть'), ('in_process', 'В процессе'), ('watched', 'Завершён')], default='to_watch', max_length=50, verbose_name='Статус')),
                ('id_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'managed': True,
            },
        ),
    ]
