# Generated by Django 3.2 on 2022-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='name_eng',
            field=models.CharField(max_length=250, verbose_name='Английское название'),
        ),
    ]
