# Generated by Django 3.2 on 2022-06-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220618_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='url_doramatv',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='url_kinopoisk',
        ),
    ]
