# Generated by Django 3.2 on 2023-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
